In [1]:
import pandas as pd
data = pd.read_excel("Datasets//Customer Churn.xlsx", sheet_name = "Case Data")
display(data)

,ID,Customer Age (in months),Age Segment,"Churn (1 = Yes, 0 = No)",CHI Score Month 0,CHI Score 0-1,Support Cases Month 0,Support Cases 0-1,SP Month 0,SP 0-1,Logins 0-1,Blog Articles 0-1,Views 0-1,Days Since Last Login 0-1
0,1,67,3,0,0,0,0,0,0.0,0.0,0,0,0,31
1,2,67,3,0,62,4,0,0,0.0,0.0,0,0,-16,31
2,3,55,3,0,0,0,0,0,0.0,0.0,0,0,0,31
3,4,63,3,0,231,1,1,-1,3.0,0.0,167,-8,21996,0
4,5,57,3,0,43,-1,0,0,0.0,0.0,0,0,9,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6342,6343,1,1,0,0,0,0,0,0.0,0.0,0,0,0,0
6343,6344,1,1,0,0,0,0,0,0.0,0.0,0,0,0,0
6344,6345,1,1,0,0,0,0,0,0.0,0.0,0,0,0,0
6345,6346,1,1,0,0,0,0,0,0.0,0.0,0,0,0,0
6346,6347,1,1,0,0,0,0,0,0.0,0.0,0,0,0,0

In [2]:
# Defining variables...
X = pd.DataFrame(data[['Customer Age (in months)', 'CHI Score Month 0', 'CHI Score 0-1', 'Support Cases Month 0', 'Support Cases 0-1', 'SP Month 0',  'SP 0-1',  'Logins 0-1', 'Blog Articles 0-1', 'Views 0-1', ' Days Since Last Login 0-1']])
y = pd.DataFrame(data[['Churn (1 = Yes, 0 = No)']])

In [3]:
import statsmodels.api as sm

X = sm.add_constant(X)

model = sm.Logit(y, X)
result = model.fit(method='newton')

#### Evaluate the model#########

result.summary()
result.summary2()

Optimization terminated successfully.
         Current function value: 0.192243
         Iterations 8

<class 'statsmodels.iolib.summary2.Summary'>
"""
                              Results: Logit
===========================================================================
Model:               Logit                    Pseudo R-squared:  0.044
Dependent Variable:  Churn (1 = Yes, 0 = No)  AIC:               2464.3318
Date:                2022-12-01 11:01         BIC:               2545.4006
No. Observations:    6347                     Log-Likelihood:    -1220.2
Df Model:            11                       LL-Null:           -1276.6
Df Residuals:        6335                     LLR p-value:       5.0768e-19
Converged:           1.0000                   Scale:             1.0000
No. Iterations:      8.0000
---------------------------------------------------------------------------
                            Coef.  Std.Err.    z     P>|z|   [0.025  0.975]
---------------------------------------------------------------------------
const                      -2.7627   0.1069 -25.8412 0.0000 -2.9722 -2.5531
Customer Age (in months)    0.0127   0.0054   2.3659 0.0180  0.0022  0.0232
CHI Score Month 0          -0.0047   0.0012  -3.8076 0.0001 -0.0071 -0.0023
CHI Score 0-1              -0.0103   0.0025  -4.1526 0.0000 -0.0151 -0.0054
Support Cases Month 0      -0.1524   0.1049  -1.4523 0.1464 -0.3580  0.0533
Support Cases 0-1           0.1703   0.0905   1.8814 0.0599 -0.0071  0.3476
SP Month 0                  0.0159   0.1022   0.1559 0.8761 -0.1843  0.2162
SP 0-1                     -0.0519   0.0785  -0.6615 0.5083 -0.2058  0.1020
Logins 0-1                  0.0003   0.0021   0.1383 0.8900 -0.0038  0.0044
Blog Articles 0-1           0.0003   0.0196   0.0148 0.9882 -0.0381  0.0387
Views 0-1                  -0.0001   0.0000  -2.6966 0.0070 -0.0002 -0.0000
 Days Since Last Login 0-1  0.0172   0.0043   4.0203 0.0001  0.0088  0.0256
===========================================================================

"""

In [4]:
# Redefining Variables...
X = pd.DataFrame(data[['Customer Age (in months)', 'CHI Score Month 0', 'CHI Score 0-1', 'Support Cases 0-1', 'Views 0-1', ' Days Since Last Login 0-1']])
X.head()

,Customer Age (in months),CHI Score Month 0,CHI Score 0-1,Support Cases 0-1,Views 0-1,Days Since Last Login 0-1
0,67,0,0,0,0,31
1,67,62,4,0,-16,31
2,55,0,0,0,0,31
3,63,231,1,-1,21996,0
4,57,43,-1,0,9,31

In [5]:
X = sm.add_constant(X)

model = sm.Logit(y, X)
result = model.fit(method='newton')

#### Evaluate the model#########

result.summary()
result.summary2()

Optimization terminated successfully.
         Current function value: 0.192639
         Iterations 7

<class 'statsmodels.iolib.summary2.Summary'>
"""
                              Results: Logit
===========================================================================
Model:               Logit                    Pseudo R-squared:  0.042
Dependent Variable:  Churn (1 = Yes, 0 = No)  AIC:               2459.3544
Date:                2022-12-01 11:01         BIC:               2506.6446
No. Observations:    6347                     Log-Likelihood:    -1222.7
Df Model:            6                        LL-Null:           -1276.6
Df Residuals:        6340                     LLR p-value:       5.9859e-21
Converged:           1.0000                   Scale:             1.0000
No. Iterations:      7.0000
---------------------------------------------------------------------------
                            Coef.  Std.Err.    z     P>|z|   [0.025  0.975]
---------------------------------------------------------------------------
const                      -2.7868   0.1052 -26.4971 0.0000 -2.9929 -2.5806
Customer Age (in months)    0.0145   0.0052   2.7916 0.0052  0.0043  0.0248
CHI Score Month 0          -0.0055   0.0011  -5.1149 0.0000 -0.0076 -0.0034
CHI Score 0-1              -0.0102   0.0023  -4.4288 0.0000 -0.0147 -0.0057
Support Cases 0-1           0.0577   0.0397   1.4533 0.1461 -0.0201  0.1355
Views 0-1                  -0.0001   0.0000  -2.6522 0.0080 -0.0002 -0.0000
 Days Since Last Login 0-1  0.0173   0.0043   4.0329 0.0001  0.0089  0.0257
===========================================================================

"""

In [6]:
# Redefining X variables again...
X = pd.DataFrame(data[['Customer Age (in months)', 'CHI Score Month 0', 'CHI Score 0-1', 'Views 0-1', ' Days Since Last Login 0-1']])
X.head()

,Customer Age (in months),CHI Score Month 0,CHI Score 0-1,Views 0-1,Days Since Last Login 0-1
0,67,0,0,0,31
1,67,62,4,-16,31
2,55,0,0,0,31
3,63,231,1,21996,0
4,57,43,-1,9,31

In [7]:
X = sm.add_constant(X)

model = sm.Logit(y, X)
result = model.fit(method='newton')

#### Evaluate the model#########

result.summary()
result.summary2()

Optimization terminated successfully.
         Current function value: 0.192801
         Iterations 7

<class 'statsmodels.iolib.summary2.Summary'>
"""
                              Results: Logit
===========================================================================
Model:               Logit                    Pseudo R-squared:  0.041
Dependent Variable:  Churn (1 = Yes, 0 = No)  AIC:               2459.4186
Date:                2022-12-01 11:01         BIC:               2499.9530
No. Observations:    6347                     Log-Likelihood:    -1223.7
Df Model:            5                        LL-Null:           -1276.6
Df Residuals:        6341                     LLR p-value:       3.3157e-21
Converged:           1.0000                   Scale:             1.0000
No. Iterations:      7.0000
---------------------------------------------------------------------------
                            Coef.  Std.Err.    z     P>|z|   [0.025  0.975]
---------------------------------------------------------------------------
const                      -2.7849   0.1051 -26.4867 0.0000 -2.9909 -2.5788
Customer Age (in months)    0.0149   0.0052   2.8756 0.0040  0.0048  0.0251
CHI Score Month 0          -0.0056   0.0011  -5.2114 0.0000 -0.0077 -0.0035
CHI Score 0-1              -0.0094   0.0023  -4.1890 0.0000 -0.0138 -0.0050
Views 0-1                  -0.0001   0.0000  -2.8286 0.0047 -0.0002 -0.0000
 Days Since Last Login 0-1  0.0171   0.0043   4.0012 0.0001  0.0087  0.0255
===========================================================================

"""

#### Model Fitting using the Age Segments categories...

In [8]:
# selecting rows based on condition customer age group 1
group1_df = data.loc[data["Age Segment"] == 1]
display(group1_df.head())


# selecting rows based on condition customer age group 2
group2_df = data.loc[data["Age Segment"] == 2]
display(group2_df.head())


# selecting rows based on condition customer age group 3
group3_df = data.loc[data["Age Segment"] == 3]
display(group3_df.head())

,ID,Customer Age (in months),Age Segment,"Churn (1 = Yes, 0 = No)",CHI Score Month 0,CHI Score 0-1,Support Cases Month 0,Support Cases 0-1,SP Month 0,SP 0-1,Logins 0-1,Blog Articles 0-1,Views 0-1,Days Since Last Login 0-1
164,165,1,1,0,0,0,0,0,0.0,0.0,0,0,0,0
243,244,1,1,0,0,0,0,0,0.0,0.0,0,0,0,0
253,254,1,1,0,0,0,0,0,0.0,0.0,0,0,0,0
276,277,5,1,0,112,3,0,-2,0.0,-3.0,36,-2,1490,0
314,315,6,1,0,20,-1,0,0,0.0,0.0,-2,0,15,4

,ID,Customer Age (in months),Age Segment,"Churn (1 = Yes, 0 = No)",CHI Score Month 0,CHI Score 0-1,Support Cases Month 0,Support Cases 0-1,SP Month 0,SP 0-1,Logins 0-1,Blog Articles 0-1,Views 0-1,Days Since Last Login 0-1
207,208,7,2,0,141,22,2,1,3.0,0.0,70,0,72,-3
210,211,12,2,1,143,37,0,0,0.0,0.0,50,3,18,28
216,217,12,2,0,215,8,2,1,3.0,1.0,17,-4,4914,0
218,219,11,2,0,158,32,0,0,0.0,0.0,33,0,-41,0
219,220,11,2,0,87,20,0,0,0.0,0.0,27,0,-76,0

,ID,Customer Age (in months),Age Segment,"Churn (1 = Yes, 0 = No)",CHI Score Month 0,CHI Score 0-1,Support Cases Month 0,Support Cases 0-1,SP Month 0,SP 0-1,Logins 0-1,Blog Articles 0-1,Views 0-1,Days Since Last Login 0-1
0,1,67,3,0,0,0,0,0,0.0,0.0,0,0,0,31
1,2,67,3,0,62,4,0,0,0.0,0.0,0,0,-16,31
2,3,55,3,0,0,0,0,0,0.0,0.0,0,0,0,31
3,4,63,3,0,231,1,1,-1,3.0,0.0,167,-8,21996,0
4,5,57,3,0,43,-1,0,0,0.0,0.0,0,0,9,31

1. Model fitting for Age Segment-1 (Age < 7 Months)

In [24]:
# (AGE GROUP-1 => Age < 7 months)
# Defining variables for model fitting... 
X1 = pd.DataFrame(group1_df[['Customer Age (in months)', 'CHI Score Month 0', 'CHI Score 0-1', 'Support Cases Month 0', 'Support Cases 0-1', 'SP Month 0',  'SP 0-1',  'Logins 0-1', 'Blog Articles 0-1', 'Views 0-1', ' Days Since Last Login 0-1']])
y = pd.DataFrame(group1_df[['Churn (1 = Yes, 0 = No)']])

display(X1.head())
display(y.head())

,Customer Age (in months),CHI Score Month 0,CHI Score 0-1,Support Cases Month 0,Support Cases 0-1,SP Month 0,SP 0-1,Logins 0-1,Blog Articles 0-1,Views 0-1,Days Since Last Login 0-1
164,1,0,0,0,0,0.0,0.0,0,0,0,0
243,1,0,0,0,0,0.0,0.0,0,0,0,0
253,1,0,0,0,0,0.0,0.0,0,0,0,0
276,5,112,3,0,-2,0.0,-3.0,36,-2,1490,0
314,6,20,-1,0,0,0.0,0.0,-2,0,15,4

     Churn (1 = Yes, 0 = No)
164                        0
243                        0
253                        0
276                        0
314                        0

In [25]:
X1 = sm.add_constant(X1)

model = sm.Logit(y, X1)
result = model.fit(method='newton')

#### Evaluate the model#########

result.summary()
result.summary2()

Optimization terminated successfully.
         Current function value: 0.092806
         Iterations 9

<class 'statsmodels.iolib.summary2.Summary'>
"""
                              Results: Logit
===========================================================================
Model:               Logit                    Pseudo R-squared:  0.105
Dependent Variable:  Churn (1 = Yes, 0 = No)  AIC:               404.6896
Date:                2022-12-01 11:28         BIC:               472.2026
No. Observations:    2051                     Log-Likelihood:    -190.34
Df Model:            11                       LL-Null:           -212.57
Df Residuals:        2039                     LLR p-value:       6.0699e-06
Converged:           1.0000                   Scale:             1.0000
No. Iterations:      9.0000
---------------------------------------------------------------------------
                            Coef.  Std.Err.    z     P>|z|   [0.025  0.975]
---------------------------------------------------------------------------
const                      -5.3901   0.5046 -10.6819 0.0000 -6.3790 -4.4011
Customer Age (in months)    0.3883   0.1330   2.9192 0.0035  0.1276  0.6490
CHI Score Month 0          -0.0052   0.0046  -1.1346 0.2566 -0.0142  0.0038
CHI Score 0-1              -0.0191   0.0063  -3.0405 0.0024 -0.0314 -0.0068
Support Cases Month 0      -0.1869   0.1567  -1.1925 0.2330 -0.4941  0.1203
Support Cases 0-1           0.2467   0.1455   1.6953 0.0900 -0.0385  0.5319
SP Month 0                  0.3607   0.2013   1.7915 0.0732 -0.0339  0.7553
SP 0-1                     -0.2254   0.1571  -1.4350 0.1513 -0.5332  0.0825
Logins 0-1                  0.0072   0.0031   2.3651 0.0180  0.0012  0.0132
Blog Articles 0-1          -0.0016   0.0279  -0.0591 0.9529 -0.0563  0.0530
Views 0-1                   0.0001   0.0002   0.5856 0.5581 -0.0002  0.0004
 Days Since Last Login 0-1  0.0355   0.0201   1.7645 0.0776 -0.0039  0.0750
===========================================================================

"""

In [26]:
# Reforming X variable keeping only the significant variables based on above model output...
X1 = pd.DataFrame(group1_df[['Customer Age (in months)', 'CHI Score 0-1', 'Logins 0-1']])

In [27]:
X1 = sm.add_constant(X1)

model = sm.Logit(y, X1)
result = model.fit(method='newton')

#### Evaluate the model#########

result.summary()
result.summary2()

Optimization terminated successfully.
         Current function value: 0.095898
         Iterations 9

<class 'statsmodels.iolib.summary2.Summary'>
"""
                             Results: Logit
=========================================================================
Model:               Logit                   Pseudo R-squared: 0.075
Dependent Variable:  Churn (1 = Yes, 0 = No) AIC:              401.3738
Date:                2022-12-01 11:28        BIC:              423.8781
No. Observations:    2051                    Log-Likelihood:   -196.69
Df Model:            3                       LL-Null:          -212.57
Df Residuals:        2047                    LLR p-value:      5.8739e-07
Converged:           1.0000                  Scale:            1.0000
No. Iterations:      9.0000
-------------------------------------------------------------------------
                          Coef.  Std.Err.    z     P>|z|   [0.025  0.975]
-------------------------------------------------------------------------
const                    -5.2820   0.4678 -11.2907 0.0000 -6.1989 -4.3650
Customer Age (in months)  0.3750   0.0978   3.8334 0.0001  0.1833  0.5668
CHI Score 0-1            -0.0178   0.0054  -3.2973 0.0010 -0.0284 -0.0072
Logins 0-1                0.0061   0.0027   2.2517 0.0243  0.0008  0.0114
=========================================================================

"""

2. Model fitting for Age Segment-1 (7 months < Age < 13 Months)

In [28]:
# Defining variables for model fitting...
X2 = pd.DataFrame(group2_df[['Customer Age (in months)', 'CHI Score Month 0', 'CHI Score 0-1', 'Support Cases Month 0', 'Support Cases 0-1', 'SP Month 0',  'SP 0-1',  'Logins 0-1', 'Blog Articles 0-1', 'Views 0-1', ' Days Since Last Login 0-1']])
y = pd.DataFrame(group2_df[['Churn (1 = Yes, 0 = No)']])

display(X2.head())
display(y.head())

,Customer Age (in months),CHI Score Month 0,CHI Score 0-1,Support Cases Month 0,Support Cases 0-1,SP Month 0,SP 0-1,Logins 0-1,Blog Articles 0-1,Views 0-1,Days Since Last Login 0-1
207,7,141,22,2,1,3.0,0.0,70,0,72,-3
210,12,143,37,0,0,0.0,0.0,50,3,18,28
216,12,215,8,2,1,3.0,1.0,17,-4,4914,0
218,11,158,32,0,0,0.0,0.0,33,0,-41,0
219,11,87,20,0,0,0.0,0.0,27,0,-76,0

     Churn (1 = Yes, 0 = No)
207                        0
210                        1
216                        0
218                        0
219                        0

In [29]:
X2 = sm.add_constant(X2)

model = sm.Logit(y, X2)
result = model.fit(method='newton')

#### Evaluate the model#########

result.summary()
result.summary2()

Optimization terminated successfully.
         Current function value: 0.226289
         Iterations 9

<class 'statsmodels.iolib.summary2.Summary'>
"""
                              Results: Logit
==========================================================================
Model:                Logit                   Pseudo R-squared: 0.137
Dependent Variable:   Churn (1 = Yes, 0 = No) AIC:              708.7498
Date:                 2022-12-01 11:28        BIC:              772.6120
No. Observations:     1513                    Log-Likelihood:   -342.37
Df Model:             11                      LL-Null:          -396.79
Df Residuals:         1501                    LLR p-value:      3.1297e-18
Converged:            1.0000                  Scale:            1.0000
No. Iterations:       9.0000
--------------------------------------------------------------------------
                            Coef.  Std.Err.    z    P>|z|   [0.025  0.975]
--------------------------------------------------------------------------
const                      -4.8192   0.6897 -6.9873 0.0000 -6.1710 -3.4674
Customer Age (in months)    0.3187   0.0650  4.9069 0.0000  0.1914  0.4460
CHI Score Month 0          -0.0098   0.0023 -4.2772 0.0000 -0.0144 -0.0053
CHI Score 0-1              -0.0034   0.0047 -0.7245 0.4688 -0.0125  0.0058
Support Cases Month 0      -0.1772   0.2521 -0.7026 0.4823 -0.6714  0.3170
Support Cases 0-1           0.1339   0.1824  0.7343 0.4628 -0.2236  0.4914
SP Month 0                 -0.1828   0.2095 -0.8723 0.3830 -0.5935  0.2279
SP 0-1                      0.0200   0.1458  0.1372 0.8909 -0.2658  0.3058
Logins 0-1                 -0.0001   0.0041 -0.0237 0.9811 -0.0081  0.0079
Blog Articles 0-1          -0.0475   0.0616 -0.7710 0.4407 -0.1683  0.0733
Views 0-1                  -0.0001   0.0001 -2.3191 0.0204 -0.0002 -0.0000
 Days Since Last Login 0-1  0.0147   0.0066  2.2402 0.0251  0.0018  0.0275
==========================================================================

"""

In [30]:
# Reforming X variable keeping only the significant variables based on above model output...
X2 = pd.DataFrame(group2_df[['Customer Age (in months)', 'CHI Score Month 0', 'Views 0-1', ' Days Since Last Login 0-1']])

In [31]:
X2 = sm.add_constant(X2)

model = sm.Logit(y, X2)
result = model.fit(method='newton')

#### Evaluate the model#########

result.summary()
result.summary2()

Optimization terminated successfully.
         Current function value: 0.229071
         Iterations 8

<class 'statsmodels.iolib.summary2.Summary'>
"""
                              Results: Logit
==========================================================================
Model:                Logit                   Pseudo R-squared: 0.127
Dependent Variable:   Churn (1 = Yes, 0 = No) AIC:              703.1674
Date:                 2022-12-01 11:30        BIC:              729.7766
No. Observations:     1513                    Log-Likelihood:   -346.58
Df Model:             4                       LL-Null:          -396.79
Df Residuals:         1508                    LLR p-value:      8.0167e-21
Converged:            1.0000                  Scale:            1.0000
No. Iterations:       8.0000
--------------------------------------------------------------------------
                            Coef.  Std.Err.    z    P>|z|   [0.025  0.975]
--------------------------------------------------------------------------
const                      -4.9052   0.6782 -7.2330 0.0000 -6.2344 -3.5760
Customer Age (in months)    0.3287   0.0643  5.1135 0.0000  0.2027  0.4546
CHI Score Month 0          -0.0122   0.0020 -6.0457 0.0000 -0.0161 -0.0082
Views 0-1                  -0.0001   0.0001 -2.2909 0.0220 -0.0002 -0.0000
 Days Since Last Login 0-1  0.0141   0.0062  2.2524 0.0243  0.0018  0.0263
==========================================================================

"""

3. Model fitting for Age Segment-1 (Age > 13 Months)

In [32]:
# Defining variables for model fitting...
X3 = pd.DataFrame(group3_df[['Customer Age (in months)', 'CHI Score Month 0', 'CHI Score 0-1', 'Support Cases Month 0', 'Support Cases 0-1', 'SP Month 0',  'SP 0-1',  'Logins 0-1', 'Blog Articles 0-1', 'Views 0-1', ' Days Since Last Login 0-1']])
y = pd.DataFrame(group3_df[['Churn (1 = Yes, 0 = No)']])

display(X3.head())
display(y.head())

,Customer Age (in months),CHI Score Month 0,CHI Score 0-1,Support Cases Month 0,Support Cases 0-1,SP Month 0,SP 0-1,Logins 0-1,Blog Articles 0-1,Views 0-1,Days Since Last Login 0-1
0,67,0,0,0,0,0.0,0.0,0,0,0,31
1,67,62,4,0,0,0.0,0.0,0,0,-16,31
2,55,0,0,0,0,0.0,0.0,0,0,0,31
3,63,231,1,1,-1,3.0,0.0,167,-8,21996,0
4,57,43,-1,0,0,0.0,0.0,0,0,9,31

   Churn (1 = Yes, 0 = No)
0                        0
1                        0
2                        0
3                        0
4                        0

In [33]:
X3 = sm.add_constant(X3)

model = sm.Logit(y, X3)
result = model.fit(method='newton')

#### Evaluate the model#########

result.summary()
result.summary2()

Optimization terminated successfully.
         Current function value: 0.209795
         Iterations 8

<class 'statsmodels.iolib.summary2.Summary'>
"""
                              Results: Logit
==========================================================================
Model:                Logit                   Pseudo R-squared: 0.080
Dependent Variable:   Churn (1 = Yes, 0 = No) AIC:              1191.7175
Date:                 2022-12-01 11:30        BIC:              1262.8930
No. Observations:     2783                    Log-Likelihood:   -583.86
Df Model:             11                      LL-Null:          -634.45
Df Residuals:         2771                    LLR p-value:      1.0376e-16
Converged:            1.0000                  Scale:            1.0000
No. Iterations:       8.0000
--------------------------------------------------------------------------
                            Coef.  Std.Err.    z    P>|z|   [0.025  0.975]
--------------------------------------------------------------------------
const                      -0.7271   0.2650 -2.7440 0.0061 -1.2465 -0.2077
Customer Age (in months)   -0.0398   0.0100 -3.9824 0.0001 -0.0594 -0.0202
CHI Score Month 0          -0.0115   0.0017 -6.7278 0.0000 -0.0148 -0.0081
CHI Score 0-1               0.0000   0.0036  0.0075 0.9940 -0.0070  0.0070
Support Cases Month 0      -0.0997   0.1927 -0.5174 0.6048 -0.4773  0.2779
Support Cases 0-1           0.0844   0.1531  0.5511 0.5816 -0.2158  0.3846
SP Month 0                 -0.0385   0.1649 -0.2337 0.8152 -0.3617  0.2846
SP 0-1                      0.0475   0.1237  0.3843 0.7007 -0.1949  0.2900
Logins 0-1                 -0.0038   0.0042 -0.9072 0.3643 -0.0121  0.0045
Blog Articles 0-1           0.0138   0.0290  0.4748 0.6350 -0.0431  0.0706
Views 0-1                  -0.0001   0.0001 -1.5794 0.1142 -0.0003  0.0000
 Days Since Last Login 0-1  0.0005   0.0033  0.1623 0.8711 -0.0059  0.0070
==========================================================================

"""

In [34]:
# Reforming X variable keeping only the significant variables based on above model output...
X3 = pd.DataFrame(group3_df[['Customer Age (in months)', 'CHI Score Month 0']])

In [35]:
X3 = sm.add_constant(X3)

model = sm.Logit(y, X3)
result = model.fit(method='newton')

#### Evaluate the model#########

result.summary()
result.summary2()

Optimization terminated successfully.
         Current function value: 0.210640
         Iterations 8

<class 'statsmodels.iolib.summary2.Summary'>
"""
                             Results: Logit
========================================================================
Model:              Logit                   Pseudo R-squared: 0.076
Dependent Variable: Churn (1 = Yes, 0 = No) AIC:              1178.4236
Date:               2022-12-01 11:32        BIC:              1196.2174
No. Observations:   2783                    Log-Likelihood:   -586.21
Df Model:           2                       LL-Null:          -634.45
Df Residuals:       2780                    LLR p-value:      1.1187e-21
Converged:          1.0000                  Scale:            1.0000
No. Iterations:     8.0000
------------------------------------------------------------------------
                          Coef.  Std.Err.    z    P>|z|   [0.025  0.975]
------------------------------------------------------------------------
const                    -0.7442   0.2552 -2.9165 0.0035 -1.2444 -0.2441
Customer Age (in months) -0.0383   0.0099 -3.8752 0.0001 -0.0577 -0.0189
CHI Score Month 0        -0.0126   0.0015 -8.5897 0.0000 -0.0154 -0.0097
========================================================================

"""